### PR TITLE
Fix furry stuff

### PR DESCRIPTION
**Pull request by VasilisThePikachu**
The website is e621 not e631 and yiff to yif

Don't let us furries get away easy

### CODE REVIEW

**Comment by john482847573** [comment]
How do you know that? 🤨

**Comment by ghost** [comment]
well,

**Comment by VasilisThePikachu** [comment]
> How do you know that? 🤨

Literally in my pr description

> Dont let **us furries** get away easy

Also if my name and profile was not enough

**Review by puppy0cam — APPROVED** [review]
lgtm

**Comment by OllieRG525** [comment]
To all my fellow furries, I hate that i was about to make this

**Comment by VasilisThePikachu** [comment]
This is never getting merged and my pr's section always has this open I wanna get rid of it sorry patch the game yourselves nerds

**Pull request closed without merging**
